---
- include_vars: "/vagrant/settings.yml"

- name: Get node name
  ansible.builtin.shell: hostname -s
  register: nodename
  changed_when: false
  check_mode: false
  become: false

- name: Kubeadm pull images
  ansible.builtin.command: kubeadm config images pull
  become: true

- name: Initialize the control plane
  ansible.builtin.command: kubeadm init --apiserver-advertise-address={{ cluster.network.control_ip }} --apiserver-cert-extra-sans={{ cluster.network.control_ip }} --pod-network-cidr={{ cluster.network.pod_cidr }} --service-cidr={{ cluster.network.service_cidr }} --node-name "{{ nodename.stdout }}"
  become: true

- name: Create .kube directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

- name: Copy admin.conf to .kube directory
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Copy admin.conf to /vagrant directory
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /vagrant/admin.conf
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Ensure {{ config_path }} directory exists
  ansible.builtin.file:
    path: "{{ config_path }}"
    state: directory
  become: true

- name: Copy admin.conf to {{ config_path }} directory
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ config_path }}/admin.conf"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Create {{ config_path }}/join.sh
  ansible.builtin.shell: kubeadm token create --print-join-command > {{ config_path }}/join.sh
  become: true

# curl https://raw.githubusercontent.com/projectcalico/calico/v${CALICO_VERSION}/manifests/calico.yaml -O
- name: Download Calico manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v{{ cluster.software.calico }}/manifests/calico.yaml
    dest: "{{ config_path }}/calico.yaml"
    mode: '0644'
  become: true

- name: Apply Calico manifest
  ansible.builtin.command: kubectl apply -f {{ config_path }}/calico.yaml
  register: result
  until: result is succeeded
  retries: 5
  delay: 15
  become: true

- name: Taint control plane nodes
  ansible.builtin.command: kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule-
  when: cluster.nodes.control_plane.enable_scheduling is defined and cluster.nodes.control_plane.enable_scheduling == true
  become: true

- name: Create a k alias for kubectl
  ansible.builtin.shell: echo "alias k='kubectl'" >> /home/{{ ansible_user }}/.bashrc
  become: true
