---
ansible:
  version: 2.16.0
  folder_path: /home/vagrant/ansible
vagrant:
  boot_timeout: 600
  box_name: bento/ubuntu-22.04
  box_version: 202309.08.0
  log_level: DEBUG
  provider: virtualbox
  timezone: Europe/Madrid
  keyboard: es
virtual_box:
  vm_group_name: VGK8S Kubernetes Cluster
  network:
    hostname_prefix: vgk8s-
    private_ip: 10.0.0.10
cluster:
  software:
    calico: 3.26.0
    kubernetes: 1.27.8-1.1
    os: xUbuntu_22.04
  network:
    control_ip: 10.0.0.10
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    pod_cidr: 172.16.1.0/16
    service_cidr: 172.17.1.0/18
  nodes:
    control_plane:
      cpu: 2
      memory: 4096
      enable_scheduling: false
    workers:
      count: 1
      cpu: 2
      memory: 4096

