---
shared_folder:
  smb:
    username: jpard
charts:
  folder_path: /charts
ansible:
  version: 2.16.0
  folder_path: /ansible
  ansible_provider: guest # host or guest
grafana:
  adminPassword: "admin"
  namespace: monitoring
vagrant:
  boot_timeout: 600
  box_name: roboxes/ubuntu2204
  box_version: "4.3.2"
  log_level: DEBUG
  provider: hyperv # virtualbox vmware_desktop hyperv
  timezone: Europe/Madrid
  keyboard_layout: es
  is_windows_wsl: false
  folder_path: /vagrant
virtual_box:
  vm_group_name: VGK8S Kubernetes Cluster
  network:
    hostname_prefix: vgk8s-
    private_ip: 172.20.119.112
    nic_type: virtio
cluster:
  software:
    calico: 3.26.0
    kubernetes: 1.27.8-1.1
    os: xUbuntu_22.04
  network:
    control_ip: 172.20.119.112
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    pod_cidr: 172.16.1.0/16
    service_cidr: 172.17.0.0/16
    metallb:
      start: 172.20.119.112
      end: 172.20.119.112
  nodes:
    control_plane:
      cpu: 4
      memory: 8192
      enable_scheduling: true
    workers:
      count: 0
      cpu: 4
      memory: 4096

