---
charts:
  folder_path: /charts
ansible:
  version: 2.16.0
  folder_path: /ansible
  ansible_provider: host # host or guest
vagrant:
  boot_timeout: 600
  box_name: bento/ubuntu-22.04
  box_version: 202303.13.0
  log_level: DEBUG
  provider: virtualbox
  timezone: Europe/Madrid
  keyboard_layout: es
  is_windows_wsl: true
virtual_box:
  vm_group_name: VGK8S Kubernetes Cluster
  network:
    hostname_prefix: vgk8s-
    private_ip: 192.168.56.100
    nic_type: Am79C973 # intel seems to cause problems with alder lake processors reseting network adapter randomly NAT: Can't allocate mbuf
cluster:
  software:
    calico: 3.26.0
    kubernetes: 1.27.8-1.1
    os: xUbuntu_22.04
  network:
    control_ip: 192.168.56.100
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    pod_cidr: 172.16.1.0/16
    service_cidr: 172.17.0.0/16
    metallb:
      start: 192.168.56.100
      end: 192.168.56.100
  nodes:
    control_plane:
      cpu: 4
      memory: 8192
      enable_scheduling: true
    workers:
      count: 0
      cpu: 4
      memory: 4096

