# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative 'src/lib/string'
require_relative 'src/lib/constants'
require_relative 'src/lib/utils'
require_relative 'src/lib/validator'

Utils.print_banner()

Validator.check_required_plugins_are_installed()

Vagrant.configure("2") do |config|

    config.env.enable
    config.timezone.value = ENV.fetch('ENV_TIMEZONE',:host)
  
    Validator.check_if_required_environment_variables_exist()
    Validator.check_if_work_dir_exists()
end