# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative 'src/lib/string'
require_relative 'src/lib/constants'
require_relative 'src/lib/custom_logger'
require_relative 'src/lib/node'
require_relative 'src/lib/utils'
require_relative 'src/lib/validator'

Utils.print_banner()

Validator.check_required_plugins_are_installed()

Vagrant.configure("2") do |config|
    # config.timezone.value = CONSTANTS::VAGRANT_TIMEZONE
  
    Validator.check_if_box_is_supported()
    Validator.check_if_provider_is_supported()

    Node.create_control_server(config)
    Node.create_workers(config)
end