---
- name: Load settings.yml
  ansible.builtin.include_vars: "{{ settings_file_path }}"

- name: Create namespace traefik-v2
  ansible.builtin.command: "kubectl create namespace traefik-v2"

- name: Add helm repo add traefik
  ansible.builtin.command: "helm repo add traefik https://traefik.github.io/charts"

- name: helm install traefik traefik/traefik --namespace=traefik-v2
  ansible.builtin.command: "helm install traefik traefik/traefik --namespace=traefik-v2"


# Configure traefik to use Let's Encrypt, using acme staging server
# - name: Configure traefik to use Let's Encrypt, using acme staging server
#   ansible.builtin.shell: |
#     cat <<EOF > {{ config_path }}/traefik-values.yaml
#     additionalArguments:
#       - "--log.level=DEBUG"
#       - "--certificatesresolvers.le.acme.email=jpardinas23@gmail.com"
#       - "--certificatesresolvers.le.acme.storage=/vagrant/config/acme.json"
#       - "--certificatesresolvers.le.acme.tlschallenge=true"
#       - "--certificatesresolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
#     EOF

# - name: Update traefik helm chart
#   ansible.builtin.command: "helm upgrade traefik traefik/traefik --namespace=traefik-v2 -f {{ config_path }}/traefik-values.yaml"
#   become: false

- name: Create traefik-dashboard service into {{ config_path }} directory
  ansible.builtin.shell: |
    cat <<EOF > {{ config_path }}/traefik-dashboard-svc.yaml
    apiVersion: v1
    kind: Service
    metadata:
      name: traefik-dashboard
      namespace: traefik-v2
    spec:
      selector:
        app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000
    EOF

- name: Create Service for Traefik Dashboard
  ansible.builtin.command: "kubectl apply -f {{ config_path }}/traefik-dashboard-svc.yaml"
  become: false

- name: Create traefik dashboard IngressRoute into {{ config_path }} directory
  ansible.builtin.shell: |
    cat <<EOF > {{ config_path }}/traefik-dashboard.yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: traefik-dashboard
      namespace: traefik-v2
    spec:
      rules:
        - host: traefik.vgk8s.com
          http:
            paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    name: traefik-dashboard
                    port:
                      number: 9000
    EOF

- name: Create IngressRoute for Traefik Dashboard
  ansible.builtin.command: "kubectl apply -f {{ config_path }}/traefik-dashboard.yaml"
  become: false

- name: Update /etc/hosts with traefik.vgk8s.com
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ cluster.network.control_ip }} traefik.vgk8s.com"

