collections:
  - name: community.general
    version: 7.4.0

  - name: vgk8s.infrastructure
    type: dir
    source: /mnt/c/Users/jpard/Desktop/project/vgk8s/ansible/collections/vgk8s/infrastructure

  - name: vgk8s.utils
    type: dir
    source: /mnt/c/Users/jpard/Desktop/project/vgk8s/ansible/collections/vgk8s/utils
