---
- hosts: REPLACE_MASTER_HOST
  become: false
  vars:
    settings_file_path: REPLACE_SETTINGS_FILE_PATH
  tasks:
    - include_role:
        name: vgk8s.utils.helm
    - include_role:
        name: vgk8s.infrastructure.common
    - include_role:
        name: vgk8s.infrastructure.k8s
    - include_role:
        name: vgk8s.infrastructure.calico
    - include_role:
        name: vgk8s.infrastructure.nfspvc
    - include_role:
        name: vgk8s.infrastructure.metallb
    - include_role:
        name: vgk8s.infrastructure.traefik
    - include_role:
        name: vgk8s.infrastructure.prometheus
    - include_role:
        name: vgk8s.infrastructure.argocd
