---
- hosts: REPLACE_MASTER_HOST
  become: false
  tasks:
    - include_role:
        name: vgk8s.utils.helm
    - include_role:
        name: vgk8s.infrastructure.common
    - include_role:
        name: vgk8s.infrastructure.k8s