---
- name: Join cluster
  ansible.builtin.shell: /bin/bash {{ config_path }}/join.sh -v
  become: true

- name: Get node name
  ansible.builtin.shell: hostname -s
  register: nodename
  changed_when: false
  check_mode: false
  become: false

- name: Create .kube directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true

- name: Copy {{ config_path }}/config to .kube directory
  become: true
  ansible.builtin.copy:
    src: "{{ config_path }}/admin.conf"
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Label node as worker
  ansible.builtin.command: kubectl label node {{ nodename.stdout }} node-role.kubernetes.io/worker=worker
  become: false