---
- name: Load settings.yml
  ansible.builtin.include_vars: "{{ settings_file_path }}"

- name: Install NFS Server
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - nfs-kernel-server

- name: Create NFS directory
  become: true
  ansible.builtin.file:
    path: /mnt/nfs_share
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Add NFS directory to exports
  become: true
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "/mnt/nfs_share *(rw,sync,no_subtree_check,no_root_squash)"
    create: yes
    owner: root
    group: root
    mode: '0644'
  
- name: Restart NFS Server
  become: true
  ansible.builtin.service:
    name: nfs-kernel-server
    daemon_reload: yes
    state: restarted

# Setup NFS Client Provisioner
- name: Create namespace nfs-storage
  ansible.builtin.command: "kubectl create namespace nfs-storage"

- name: Add helm repo add nfs-subdir-external-provisioner
  ansible.builtin.command: "helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"

- name: helm repo update
  ansible.builtin.command: "helm repo update"

- name: helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server={{ ansible_eth1.ipv4.address }} --set nfs.path=/mnt/nfs_share --namespace nfs-storage
  ansible.builtin.command: "helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server={{ ansible_eth1.ipv4.address }} --set nfs.path=/mnt/nfs_share --namespace nfs-storage --set storageClass.defaultClass=true"
