---
- name: Load settings.yml
  ansible.builtin.include_vars: "{{ settings_file_path }}"

- name: Create namespace argocd
  ansible.builtin.command: "kubectl create namespace argocd"
  become: false

- name: Add helm repo add argo
  ansible.builtin.command: "helm repo add argo-cd https://argoproj.github.io/argo-helm"
  become: false

- name: Helm dep update
  ansible.builtin.command: "helm dep update /charts/argocd/"
  become: false

- name: Install argocd
  ansible.builtin.command: "helm install argo-cd /charts/argocd/ --namespace argocd"
  become: false

- name: Get argocd password
  ansible.builtin.command: "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d"
  register: argocd_password
  become: false

- name: Create Ingress for argocd
  ansible.builtin.command: "kubectl apply -f /charts/argocd/Ingress.yaml"
  become: false