apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitness-pv
  namespace: gitness
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  nfs:
    server: 172.20.116.2
    path: /mnt/nfs_share/gitness
  volumeMode: Filesystem