apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitness.fullname" . }}
  namespace: gitness
  labels:
    {{- include "gitness.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
    - name: https
      port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.targetport2 }}
  selector:
    {{- include "gitness.selectorLabels" . | nindent 4 }} # you can find this in the templates/_helpers.tpl file
