apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitness.fullname" . }}
  namespace: gitness
  labels:
    {{- include "gitness.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "gitness.selectorLabels" . | nindent 4 }} # you can find this in the templates/_helpers.tpl file
